# -*- coding: UTF-8 -*-

'''
Module
    motion_command_formatter.py
Copyright
    Copyright (C) 2026 Vladimir Roncevic <elektron.ronca@gmail.com>
    scarajectory is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    scarajectory is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU General Public License for more details.
    You should have received a copy of the GNU General Public License along
    with this program. If not, see <http://www.gnu.org/licenses/>.
Info
    Motion and trajectory command packet encoder for SCARA microcontroller.
'''

from __future__ import annotations

from collections.abc import Sequence

from scarajectory.core.model.trajectory.waypoint import Waypoint
from scarajectory.infrastructure.formatter.command_templates import CommandTemplates

__author__ = 'Vladimir Roncevic'
__copyright__ = '(C) 2026, https://vroncevic.github.io/scarajectory'
__credits__ = ['Vladimir Roncevic', 'Python Software Foundation']
__license__ = 'https://github.com/vroncevic/scarajectory/blob/dev/LICENSE'
__version__ = '1.0.4'
__maintainer__ = 'Vladimir Roncevic'
__email__ = 'elektron.ronca@gmail.com'
__status__ = 'Updated'


class MotionCommandFormatter:
    '''
        Formats robotic motion and trajectory execution commands using template registry.

        It defines:

            :methods:
                | format_home - Formats homing sequence command.
                | format_move - Formats waypoint motion command from Waypoint model.
                | format_waypoint_packet - Formats waypoint model into low-level firmware packet.
                | format_program - Formats sequence of waypoints into ASCII instruction stream.
    '''

    @classmethod
    def format_home(cls) -> str:
        '''
            Formats homing sequence command.

            :return: Formatted home command string.
            :exceptions: None.
        '''
        return CommandTemplates.HOME

    @classmethod
    def format_move(cls, waypoint: Waypoint) -> str:
        '''
            Formats waypoint motion command from Waypoint model.

            :param waypoint: Waypoint domain object.
            :return: Formatted move command packet string.
            :exceptions: None.
        '''
        if waypoint.command:
            return waypoint.command

        template: str = CommandTemplates.MOVE_TEMPLATE

        return template.format(
            x=waypoint.x,
            y=waypoint.y,
            z=waypoint.z,
            phi=waypoint.phi,
            speed=waypoint.speed
        )

    @classmethod
    def format_waypoint_packet(cls, waypoint: Waypoint) -> str:
        '''
            Formats waypoint model into low-level firmware wire packet.

            :param waypoint: Waypoint domain model.
            :return: Formatted packet string.
            :exceptions: None.
        '''
        if waypoint.command:
            return waypoint.command

        if abs(waypoint.phi) < 1e-4:
            return f'<pt#{waypoint.x:.2f}#{waypoint.y:.2f}#{waypoint.z:.2f}#{waypoint.speed:.1f}#end>'

        return f'<pt#{waypoint.x:.2f}#{waypoint.y:.2f}#{waypoint.z:.2f}#{waypoint.phi:.2f}#{waypoint.speed:.1f}#end>'

    @classmethod
    def format_program(cls, waypoints: Sequence[Waypoint], total_distance: float = 0.0) -> str:
        '''
            Formats sequence of waypoints into sequential ASCII firmware instruction stream.

            :param waypoints: Sequence of waypoints.
            :param total_distance: Pre-calculated total distance in mm (defaults to 0.0).
            :return: Multi-line ASCII firmware instruction stream.
            :exceptions: None.
        '''
        lines: list[str] = [
            '; --- SCARA Motion Program Generated by SCARAjectory ---',
            f'; Total Waypoints: {len(waypoints)}'
        ]

        if total_distance > 0.0:
            lines.append(f'; Total Distance: {total_distance:.2f} mm')

        lines.append(CommandTemplates.ENABLE)

        for pt in waypoints:
            lines.append(cls.format_waypoint_packet(pt))

        return '\n'.join(lines)
